//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramandoTareas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        public int id { get; set; }
        public string IdVideo { get; set; }
        public string Nombre { get; set; }
        public string Comentario1 { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Video Video { get; set; }
    }
}
