<?xml version="1.0" encoding="utf-8"?><Database Name="MeTube" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-SSQS2FG;Initial Catalog=MeTube;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MeTubeConnectionString" Provider="System.Data.SqlClient" />
</Database>